const countryballCardTiers = {
  australia: 'C',
  austria: 'A',
  belgium: 'A',
  canada: 'B',
  china: 'A',
  croatia: 'B',
  czechia: 'A',
  finland: 'C',
  france: 'B',
  germany: 'S',
  hungary: 'A',
  india: 'C',
  italy: 'A',
  japan: 'B',
  mexico: 'S',
  mongolia: 'C',
  netherlands: 'S',
  norway: 'A',
  poland: 'A',
  portugal: 'B',
  romania: 'S',
  russia: 'D',
  saudi_arabia: 'C',
  spain: 'B',
  sweden: 'B',
  switzerland: 'S',
  turkey: 'B',
  uk: 'A',
  ukraine: 'A',
  us: 'B'
};

window.countryballGalleryCards = [
  ['australia', 'Australia', 'A flexible countryball card ready for risky plays and late-game turns.'],
  ['austria', 'Austria', 'A tidy gallery entry for a card that likes careful setup before the table gets loud.'],
  ['belgium', 'Belgium', 'A compact card page for one of the roster picks in the base gallery.'],
  ['canada', 'Canada', 'A steady countryball pick with room for players to add matchup notes later.'],
  ['china', 'China', 'A heavyweight gallery card that deserves a closer look at the art and table role.'],
  ['croatia', 'Croatia', 'A sharp roster entry for players comparing countryball options.'],
  ['czechia', 'Czechia', 'A clean gallery page for checking the card before a match.'],
  ['finland', 'Finland', 'A cool-headed card entry with space for community strategy notes.'],
  ['france', 'France', 'A core countryball card shown here with a larger preview and quick description.'],
  ['germany', 'Germany', 'A strong roster entry for players browsing the available cards.'],
  ['hungary', 'Hungary', 'A gallery page for reviewing the card art and future comments.'],
  ['india', 'India', 'A bold countryball card entry with room for ratings and player tips later.'],
  ['italy', 'Italy', 'A bright gallery card for browsing the roster before choosing favorites.'],
  ['japan', 'Japan', 'A focused card page for viewing the art and collecting future community notes.'],
  ['mexico', 'Mexico', 'A lively roster entry ready for ratings, comments, and edits in the next version.'],
  ['mongolia', 'Mongolia', 'A distinctive card page for one of the gallery standouts.'],
  ['netherlands', 'Netherlands', 'A clean entry for comparing this countryball card with the rest of the roster.'],
  ['norway', 'Norway', 'A gallery card with space for future player strategy and match notes.'],
  ['poland', 'Poland', 'A fan-favorite style entry with larger art and a simple about page.'],
  ['portugal', 'Portugal', 'A roster page for checking out the card and future community feedback.'],
  ['romania', 'Romania', 'A countryball card entry ready for ratings and comments later.'],
  ['russia', 'Russia', 'A big roster card with a focused about panel for browsing.'],
  ['saudi_arabia', 'Saudi Arabia', 'A resourceful-looking gallery entry with room for future details.'],
  ['spain', 'Spain', 'A polished card page for browsing the art and roster position.'],
  ['sweden', 'Sweden', 'A gallery entry for checking the card before players start rating it.'],
  ['switzerland', 'Switzerland', 'A careful, defensive-feeling roster entry with room for notes.'],
  ['turkey', 'Turkey', 'A punchy countryball card entry shown with a larger detail page.'],
  ['uk', 'United Kingdom', 'A classic roster entry with a dedicated page for art and future discussion.'],
  ['ukraine', 'Ukraine', 'A gallery page for one of the roster cards, ready for future community edits.'],
  ['us', 'United States', 'A headline roster card with larger art and space for player notes.']
].map(([id, name, about]) => {
  return {
    id,
    name,
    about,
    image: `assets/card-peek/${id}.webp`,
    page: `cards/${id}.html`,
    tier: countryballCardTiers[id] || 'D'
  };
});
